import React from 'react'

const head = () => {
  return (
    <>
      <title>Popular Movies</title>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta name="description" content="Generated by Create Next App"></meta>
    </>
  )
}

export default head;